version: '3.9'

services:
  django:
    image: django-vite:django-app
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - './django_app:/app/django_app'
    env_file:
      - "./.env"

  vite_default:
    image: django-vite:vite-app
    tty: true
    ports:
      - '${DJANGO_VITE_DEV_SERVER_PORT}:${DJANGO_VITE_DEV_SERVER_PORT}'
    volumes:
      - './vite.config.js:/app/vite.config.js'
      - './django_app:/app/django_app'
    env_file:
      - "./.env"
