version: '3.9'

services:
  django:
    image: django-vite:django-app
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - './django_app/django_app:/app/django_app'
      - './vite_app_1/dist:/vite_app_1/dist'
      - './vite_app_2/dist:/vite_app_2/dist'
      - './vite_app_3/dist:/vite_app_3/dist'
    env_file:
      - "./.env"

  vite_default:
    image: django-vite:vite-app
    tty: true
    ports:
      - '${DEFAULT_DEV_SERVER_PORT}:${DEFAULT_DEV_SERVER_PORT}'
    volumes:
      - './django_app/vite.config.js:/app/vite.config.js'
      - './django_app/django_app:/app/django_app'
    env_file:
      - "./.env"

  vite_app_1:
    image: django-vite:vite-app
    tty: true
    ports:
      - '${APP1_DEV_SERVER_PORT}:${APP1_DEV_SERVER_PORT}'
    volumes:
      - './vite_app_1/vite.config.js:/app/vite.config.js'
      - './vite_app_1/src:/app/src'
    env_file:
      - "./.env"

  vite_app_2:
    image: django-vite:vite-app
    tty: true
    ports:
      - '${APP2_DEV_SERVER_PORT}:${APP2_DEV_SERVER_PORT}'
    volumes:
      - './vite_app_2/vite.config.js:/app/vite.config.js'
      - './vite_app_2/src:/app/src'
      - './vite_app_2/dist:/app/dist'
    env_file:
      - "./.env"

  vite_app_3:
    image: django-vite:vite-app
    tty: true
    ports:
      - '${APP3_DEV_SERVER_PORT}:${APP3_DEV_SERVER_PORT}'
    volumes:
      - './vite_app_3/vite.config.js:/app/vite.config.js'
      - './vite_app_3/src:/app/src'
      - './vite_app_3/dist:/app/dist'
    env_file:
      - "./.env"