version: '3.9'

services:
  vite_app_1:
    command: ["npm", "run", "build"]
    build:
      context: .
      dockerfile: ../../docker/vite.Dockerfile
      args:
        DJANGO_APP_PATH: "./django_app"
        VITE_APP_PATH: "./vite_app_1"
    tty: false
    volumes:
      - './vite_app_1/dist:/app/dist'
    env_file:
      - "./.env"

  vite_app_2:
    command: ["npm", "run", "build"]
    build:
      context: .
      dockerfile: ../../docker/vite.Dockerfile
      args:
        DJANGO_APP_PATH: "./django_app"
        VITE_APP_PATH: "./vite_app_2"
    tty: false
    volumes:
      - './vite_app_2/dist:/app/dist'
    env_file:
      - "./.env"