version: '3.9'

services:
  django:
    build:
      context: ..
      dockerfile: docker/images/django/django.Dockerfile
      args:
        APP_HOME: "${APP_HOME}"
        PROJECT_ROOT_PATH: "${PROJECT_ROOT_PATH}"
    ports:
      - '${PORT}:${PORT}'
    links:
      - vite_default:vite_default
    volumes:
      - '../${PROJECT_ROOT_PATH}/demo:${APP_HOME}/demo'
    env_file:
      - "../${PROJECT_ROOT_PATH}/.env"

  vite_default:
    build:
      context: ..
      dockerfile: docker/images/vite/vite.Dockerfile
      args:
        APP_HOME: "${APP_HOME}"
        PROJECT_ROOT_PATH: "${PROJECT_ROOT_PATH}"
        VITE_APP_PATH: "${PROJECT_ROOT_PATH}"
    tty: true
    ports:
      - '${DJANGO_VITE_DEV_SERVER_PORT}:${DJANGO_VITE_DEV_SERVER_PORT}'
    volumes:
      - '../${PROJECT_ROOT_PATH}/vite.config.js:${APP_HOME}/vite.config.js'
      - '../${PROJECT_ROOT_PATH}/tailwind.config.js:${APP_HOME}/tailwind.config.js'
      - '../${PROJECT_ROOT_PATH}/demo:${APP_HOME}/demo'
    env_file:
      - "../${PROJECT_ROOT_PATH}/.env"
